### ISSUE TITLE
Country Unknown after upgrade to 1.37.0 

### ISSUE THREAD

**Issue by miguelcss** [umami-software/umami#1445]
We started seeing country Unknown after upgrade to 1.37.0. 

We use nginx as a reverse proxy and are passing the ```X-Forwarded-For ``` property, nothing changed there. 

In debug we notice all IPs were being considered as localhost in request.js. 

Updating to use request-ip 3.3.0 started getting the correct ip again, and we have countries working again in ```session```

I wonder if there was any change to the ip fetch logic in umami and more people have same issue, happy to post PR if that is the case.

**Comment by mikecao** [comment]
The only change we made was move the location of the geo databases. Strange that updating `request-ip` fixed your issue. Sometimes, your environment may use a different header that `request-ip` doesn't check, so that's why added the `CLIENT_IP_HEADER` environment variable. See https://umami.is/docs/environment-variables

But if you have a better fix, a PR would be welcome.

**Comment by mistaya** [comment]
I also had this issue, and installing request-ip 3.3.0 fixed it - thanks!

**Comment by mikecao** [comment]
@miguelcss We will update `request-ip` to v3.3.0 in the next release. But you can do it ahead of time.

**Comment by mikecao** [comment]
Fixed in v1.38.0.
