### ISSUE TITLE
Railway:  No deploys for this service

### ISSUE THREAD

**Issue by UlyC** [umami-software/umami#1462]
1. After I click this  “Deploy on Railway” button on the document
![image](https://user-images.githubusercontent.com/36838240/186813759-e911b0aa-19a2-4079-9058-cd384216f286.png)

And set the `hash_salt` variable, services won't  be deployed
Railway report:
No deploys for this service
![image](https://user-images.githubusercontent.com/36838240/186813607-4c96eb90-f298-4916-a566-f1d29f463e2d.png)

2. The following deployment methods work for me, but need to add environment variables manually.

New Project > Deploy from repo

Note: 
`DATABASE_TYPE` default value is "postgres" , need to change to "postgresql"

**Comment by thomascenni** [comment]
@UlyC 
I made a blog post to deploy Umami with one click on Render:

https://thomascenni.com/blog/deploy-umami-on-render/

It's much more simpler than Railway because the DATABASE_URL is automatically populated and HASH_SALT is automatically generated.

Thomas

**Comment by isaacrmoreno** [comment]
@UlyC I just made a PR updating the documentation because I faced the same issue. 

Try forking + cloning down the umami repository, then try the following steps: 

### Troubleshooting

If Railway states `Your project has no deploys` within your dashboard. 

1. Select `Set up your project locally` in the bottom left hand corner of the Railway dashboard.

2. Within the `umami` root directory follow the instructions within the pop up.
  - Login to your Railway account with `railway login`
  - Link your project with `railway link`
  - Open your project dashboard with `railway open` 
  - Upload and deploy your project with `railway up`

3. Follow the **Getting started** guide starting from the [Login](https://umami.is/docs/login) step and be sure to change the default password.

I hope this gets merged/resolved soon, and helps you get your db setup
