### ISSUE TITLE
Source code telemetry.umami.is server

### ISSUE THREAD

**Issue by rubikscraft** [umami-software/umami#1518]
Hi there, the Umami server has some tracking that phones home to telemetry.umami.is. And I was wondering if the source code for this telemetry server is available somewhere?
I'm guessing this telemetry server is some fork of umami, and I'd love to use it for my own open source projects to monitor installs.

**Comment by mikecao** [comment]
Right now the telemetry server is just a script that takes whatever is passed in and throws it into a database. It is not even hooked up to Umami, so it's not really that useful.

However, we do have plans for a Links feature that will be useful. Instead of adding a website, you create a link that forwards to a destination. Basically a url shortener. Then Umami will display stats for links just like a website.
