### ISSUE TITLE
EasyList/EasyPrivacy/uBlock Origin compliant version

### ISSUE THREAD

**Issue by xplosionmind** [umami-software/umami#1835]
There are some people, like me, that do not really need to know whether someone visited their website from a laptop or from a phone (hence do not need to know the viewport dimensions), and do not need some extra information that makes [`umami.js` blocked by EasyList](https://github.com/easylist/easylist/issues/15069) and therefore in uBlock Origin too.

I was wondering if a reduced and limited version of umami.js could be created, by removing the lines of code which save [user data that are red-flagged in EasyList](https://github.com/easylist/easylist#easyprivacy).

Related to #953, #1255, and #1797

**Comment by mikecao** [comment]
The problem is ad blockers will block for whatever reason they want. Making a different "compliant" script will make no difference because they will simply block the name. You can simply rename the script to something else or use environment variables `TRACKER_SCRIPT_NAME` and `COLLECT_API_ENDPOINT`. See https://umami.is/docs/environment-variables

**Comment by xplosionmind** [comment]
Not stale! I was not following GitHub, but this issue is still very relevant!
