### ISSUE TITLE
V2 upgrade caused "Uncaught TypeError: n is null"

### ISSUE THREAD

**Issue by bjornpijnacker** [umami-software/umami#2007]
The complete error in console:

```
Uncaught TypeError: n is null
    n https://umami.<hidden>/umami.js:1
    <anonymous> https://umami.<hidden>/umami.js:1
    EventListener.handleEvent* https://umami.<hidden>/umami.js:1
    <anonymous> https://umami.<hidden>/umami.js:1
    <anonymous> https://umami.<hidden>/umami.js:1
2 umami.js:1:2063
```

Note that we renamed the script to umami.js to avoid having to change all our websites after the V2 upgrade.

This happens specifically when interacting with any Material UI input component, in our case.
We do not do any event tracking; we only load the script for page view statistics.
We know this problem was absent in V1 since our end-to-end tests are failing due to the console error.

**Comment by mikecao** [comment]
The new tracker script has a click event handler that fires on every click and checks if an underlying element has `data-umami-` attributes defined. I wonder if Material UI has it's own click handler that it is interfering with. What you can do is look for this line in the tracker:

```
document.addEventListener('click', callback, true);
```

And just comment it out since you are not using events and rebuild the tracker and see if that works. If it does we can investigate further and see what the issue is.

**Comment by mikecao** [comment]
In v2.2.0 we fixed an issue related to the tracker, so it was probably the same issue.
