### ISSUE TITLE
Cloudflare CDN nodes country collected instead of visitor's location when deployed with Vercel and using Cloudflare CDN

### ISSUE THREAD

**Issue by lwd-temp** [umami-software/umami#2129]
### Describe the Bug

Umami does not correctly record the country of visitors. For example, if a visitor is from China and connects Cloudflare CDN node in United Kingdom, Umami will record United Kingdom instead of China.

This happens when Umami is deployed on Vercel and proxied by Cloudflare CDN. Turning off Cloudflare proxy will fix this issue.

### Database

MySQL

### How are you deploying your application? (if relevant)

Vercel

**Comment by lwd-temp** [comment]
It seems that Umami does not try to get `Cf-Connecting-Ip` though the code seems to be right.

**Comment by mikecao** [comment]
If your are hosting on Vercel we use their provided headers like `x-vercel-ip-country`. This is a problem with Vercel using the wrong IP address. They are not respecting https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For. I've actually written to them in the past about this issue and they refuse to change. This is my email exchange with them:

---
Hi Vercel,

Sorry, I wasn't asking about a static IP. I was saying that your `x-forwarded-for` header is incorrect for requests that come from Cloudflare. The header does not include the IP address of the user who made the request, but instead only Cloudflare's IP address. Since you add the `x-vercel-*` headers to the request, I'm assuming you have some control over the headers that are sent. Cloudflare passes a `cf-conecting-ip` header that you can use to include in the `x-forwarded-for`.

Regards,
Mike

---

Mike,

We don't have control over Cloudflare and don't necessarily adapt our product for any specific CDN vendor. If people want to layer different proxies on top of each other, we can only accurately report the IPs that we see on our side. If anything, this is better for you so you can understand that your request is traveling through many different machines. Why would you want to "lose" information about the request?

Best,

---

Hi Vercel,

According to this documentation from Cloudflare, https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-, they should be sending you the correct x-forwarded-for header with the client IP address. It looks like you are overwriting it.

So, I created a test just to verify. I am hitting this url, https://ip-lookup.vercel.app/api/request with these headers:

> GET /api/request HTTP/1.1
> Host: [ip-lookup.vercel.app](http://ip-lookup.vercel.app/)
> User-Agent: insomnia/7.0.6
> X-Forwarded-For: 172.217.0.46, 98.138.219.231, 157.240.22.35
> Accept: */*

And these are the request headers that are received on the server:

    "host": "[ip-lookup.vercel.app](http://ip-lookup.vercel.app/)",
    "x-real-ip": "105.182.92.237",
    "accept": "*/*",
    "x-vercel-deployment-url": "[ip-lookup-l5menjt4u.vercel.app](http://ip-lookup-l5menjt4u.vercel.app/)",
    "x-forwarded-proto": "https",
    "x-forwarded-for": "105.182.92.237",
    "user-agent": "insomnia/7.0.6",
    "x-vercel-forwarded-for": "105.180.92.237",
    "x-vercel-id": "sfo1::h46mh-1595884727725-90784075bb0b",
    "x-forwarded-host": "[ip-lookup.vercel.app](http://ip-lookup.vercel.app/)",
    "connection": "close"

Note that the x-forwarded-for header does not include any of the IPs that were forwarded, only the last IP that connected. This api is not even behind Cloudflare so you are indeed rewriting the header. It is up to you how to want to handle things, but I am simply pointing out that your handling of the x-forwarded-for header is wrong.

Regards,
Mike

---

And that's where it ended. So it looks like your only option is to turn off Cloudflare CDN.

**Comment by lwd-temp** [comment]
I see... It seems that Vercel deployments does not use Geolocation DB but Vercel's country header. But Vercel's not handling things right.
Is it possible that we check `Cf-Ipcountry` before `x-vercel-ip-country`? This may fix this issue when Cloudflare and Vercel are both used.

**Comment by mikecao** [comment]
Will start using `Cf-Ipcountry` in the next release.

**Comment by lwd-temp** [comment]
That would be great.
