### ISSUE TITLE
Blank page for website stats and edit page

### ISSUE THREAD

**Issue by brunoamaral** [umami-software/umami#2269]
### Describe the Bug

In the main page I can see some stats for the last 24h but clicking 'view details' only shows a blank page and a 404 error for this url: `https://analytics.gregory-ms.com/_next/static/chunks/pages/websites/%5Bid%5D-765ca114778eb3ce.js` 

Not sure if this is relevant, but the site uses Cloudflare to speed up the JS load.

### Database

PostgreSQL

### Relevant log output

```shell
404 https://analytics.gregory-ms.com/_next/static/chunks/pages/websites/%5Bid%5D-765ca114778eb3ce.js
```

### How are you deploying your application? (if relevant)

Docker

**Comment by 0pilatos0** [comment]
Having simular issues without being behind a cloudflare environment deploying on a ubuntu server (22) with docker

[video of issue occuring in fresh install](https://cdn.discordapp.com/attachments/951899492469338164/1147533101573083156/Screen_Recording_2023-09-02_at_16.05.08.mov)

**Comment by dsyscms** [comment]
I had the same problem and solved it.

change nginx  config `proxy_pass http://umami:3000/` to `proxy_pass http://umami:3000`

**Comment by brunoamaral** [comment]
Fabulous! 😁 
Thank you @dsyscms !

**Comment by bertusdebruin** [comment]
Thanks to @adrinux, it seems like as of version 2.6. It is not possible to run Umami with an Nginx proxy and the parameter / #2287 . Since I have been running Umami on my server for more than a year including all updates > to > etc without extra /. And that's been running well all this time up to version 2.5. I't would like that: Nginx and Nginx / are the problem. Please clarify one and other in order to debug it correctly. For now and the feature.
