### ISSUE TITLE
user-agent causes stats to fail

### ISSUE THREAD

**Issue by dsyscms** [umami-software/umami#2272]
### Describe the Bug

browser: `https://www.wkbrowser.com/`
request user-agent
```
Mozilla/5.0 (Linux; Android 10; SM-G9650 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.136 Mobile Safari/537.36 JsSdk/2 NewsArticle/2.0.4 GoldBrowser/2.0.4 NetType/wifi TTWebView/1121130048408
```

response

```
{}
```

Google statistics are normal

### Database

PostgreSQL

### Which browser are you using? (if relevant)

wkbrowser

**Comment by mikecao** [comment]
Need more information. Do you mean requests to `/api/send`? Is there an error message?

**Comment by dsyscms** [comment]
request api: `/api/send`
request user-agent: `Mozilla/5.0 (Linux; Android 10; SM-G9650 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.136 Mobile Safari/537.36 JsSdk/2 NewsArticle/2.0.4 GoldBrowser/2.0.4 NetType/wifi TTWebView/1121130048408`
request payload:
```
{
  "type": "event",
  "payload": {
    "website": "7cf4caa2-6yhq-1233-8d4d-9fd1d249a388",
    "hostname": "192.168.100.2",
    "screen": "385x790",
    "language": "zh-CN",
    "title": "test",
    "url": "/",
    "referrer": ""
  }
}
```
response:
```
{}
```
when i change user-agent to `Mozilla/5.0 (Linux; Android 10; SM-G9650 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.136 Mobile Safari/537.36  GoldBrowser/2.0.4 NetType/wifi TTWebView/1121130048408` ,success

failed due to inclusion of `JsSdk/2 NewsArticle/2.0.4 `

**Comment by wfjake** [comment]
We just ran into this too, we recently upgraded from 2.5.0 to 2.6.2 and our API tracking stopped working because it wasn't sending any User-Agent header. It doesn't seem to accept any user agent, we need to spoof a browser User-Agent which is annoying and probably something that should be configurable (maybe a setting per website that enables showing stats sent from 'robots') would work?

**Comment by elfensky** [comment]
Is this expected behavior? 
Any **custom** or **uncommon** user-agent fails. 

I wanted to track internal app metrics using "events", and wanted to make a separate custom "Nodejs" useragent, but it can't do it. I have to substitute a real browser user-agent for it to work. 

This user agent works, but ideally I would want to have "appname@version" there instead. 
 
```js
export async function umamiTrackEvent(title, url, name, data = {}) {
    await fetch(`https://${process.env.UMAMI_SITE_URL}/api/send`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json', // or 'text/plain' if required
            'User-Agent':
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
        },
        body: JSON.stringify({
            type: 'event',
            payload: {
                website: process.env.UMAMI_SITE_ID,
                hostname: getHostname(),
                screen: '1x1',
                language: 'en-US',
                title: title,
                url: url,
                name: name,
                data: data,
            },
        }),
        // mode: 'cors', // optional, default for cross-origin
        // credentials: 'include', // if cookies are needed
    })
        .then((response) => response.text()) // or .json() if the response is JSON
        // .then((data) => {
        //     console.log('Response:', data);
        // })
        .catch((error) => {
            console.error('Error:', error);
        });
}
```
