### ISSUE TITLE
GET to /users fails with 405

### ISSUE THREAD

**Issue by theriftlab** [umami-software/umami#2499]
### Describe the Bug

On self-hosted Umami, when sending a GET request with admin credentials to `/users` to obtain a list of users, I am consistently getting a 405 error. This happens with Postman, Laravel / Guzzle, and your official Node API client calling `getUsers()`. Other GET /resource requests work fine (websites, teams etc.) I'm not sure if this is happening on cloud-hosted too.

It appears there is no handler for GET in `src/pages/api/users/index.ts`?

### Database

MySQL

### How are you deploying your application? (if relevant)

Local npm-based install.

**Comment by vargaslucas** [comment]
It looks like the handler was removed on this commit, https://github.com/umami-software/umami/commit/442ad61779c80224e124a580b68df12715e32100#diff-fcb32148eeb76931a5fbff94144a4fa0985821d80b713ef096e3b09e6618c357L42

And moved into: https://github.com/umami-software/umami/commit/442ad61779c80224e124a580b68df12715e32100#diff-7a7625bb52ece516e4c42122173b8f8f1d37d84f259f4bebf053f44b4c120748R47

You should be able to call `GET /admin/users` instead of `GET /users`.

Hope it helps.

**Comment by theriftlab** [comment]
Thanks, that helps.

It seems the docs & official node client are out of date - is browsing the API source the only reliable way to find all endpoints & their parameters, or is there some updated documentation somewhere?

**Comment by briancao** [comment]
We recently updated the apiClient to be reflective of our entire API.  These changes will be available to you in a few days, when we perform our latest release.  We'll be updating our API documentation at that time as well.

**Comment by theriftlab** [comment]
Great news, I'll wait for the next release. Thanks for the replies folks.
