### ISSUE TITLE
Transfer Umami but it's became a new one

### ISSUE THREAD

**Issue by mobeicanyue** [umami-software/umami#2555]
### Describe the Bug

My umami service is running on A machine. Include Umami and MySQL.
I going to transfer my umami form A vps to B vps, and I migrate mysql database from A to B.
But when I ran Umami on B (by docker compose, database is B mysql), I found that it is all new one.
Did I do something wrong?

### Database

MySQL

**Comment by franciscao633** [comment]
When you connect to mysql B database are you seeing the copied db and associated data? Since your using docker I'm wondering if your mounting the volumes correctly. The easiest way for me would be to start the container for mysql B, then dump the data afterwards using mysqldump or whatever migration method you prefer.
