### ISSUE TITLE
Documentation should clarify the definition of "bounce"

### ISSUE THREAD

**Issue by tcurdt** [umami-software/umami#2727]
### Describe the feature or enhancement

It would be good to document what defines a "bounce" in the realm of umami.

**Comment by doveg** [comment]
When I upgraded umami from 2.9 to 2.11, the bounce rate results changed significantly. 
(They were higher than I remembered.)
So I'm wondering, has the definition or calculation method changed in the latest version.

**Comment by franciscao633** [comment]
The bounce rate changed in release [v2.11.0](https://github.com/umami-software/umami/releases/tag/v2.11.0). We now calculate bounces on visits instead of sessions. If anything the bounce rate should decrease since we can correctly calculate the bounce across hourly intervals. 

We have high-level descriptions of each stat [here](https://umami.is/docs/api/website-stats#get-/api/websites/:websiteid/stats), but we can definitely improve on the definition.

**Comment by doveg** [comment]
> The bounce rate changed in release [v2.11.0](https://github.com/umami-software/umami/releases/tag/v2.11.0). We now calculate bounces on visits instead of sessions. If anything the bounce rate should decrease since we can correctly calculate the bounce across hourly intervals.
> 
> We have high-level descriptions of each stat [here](https://umami.is/docs/api/website-stats#get-/api/websites/:websiteid/stats), but we can definitely improve on the definition.

Thank you for your patient answer.
After distinguishing between visits and visitors, the data looks more accurate.
