### ISSUE TITLE
Metrics Api defaults to LIMIT 500 

### ISSUE THREAD

**Issue by dngferreira** [umami-software/umami#2730]
### Describe the Bug

Even when the number of views is higher than that it only returns 500 rows.
This makes the data that are shown on the /[websiteId}/?view=query incorrect and show different results (counts) when you apply a search.
Maybe it the LIMIT should be set to the number of views on the page.

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

v2.11.1

### How are you deploying your application? (if relevant)

Docker

**Comment by franciscao633** [comment]
I don't think its the limit 500 that's causing the issues. the limit is applied after aggregating the data so its just limiting the result set to the top 500 groupings.

![image](https://github.com/umami-software/umami/assets/31608805/4a982c7e-7d59-4130-9410-59e52a9e01b1)

The query parameters would be the only metrics where applying a search changes the counts since in our db multiple query params are under a single column.

`ref=umami-hero&utm_source=google-ads&utm_medium=paid-search&utm_campaign=GAds-Website-Analytics&utm_agid=158289285006&utm_term=website+analytics&creative=692822853771&device=m&placement=&gad_source=1&gclid=CjwKCAjwl4yyBhAgEiwADSEjeFshoDs43LnhlD3QhujLGFGUwYfMEP8z8hBXSd-5RHLGsHyrYQTFqhoCXiAQAvD_BwE`
