### ISSUE TITLE
Send CORS header with non-200 HTTP statuses too

### ISSUE THREAD

**Issue by notramo** [umami-software/umami#2735]
### Describe the Bug

`api-gateway.umami.dev` does not return an `Access-Control-Allow-Origin` header.

### Database

Umami Cloud

### Relevant log output

```shell
Umami Cloud
```

### Which Umami version are you using? (if relevant)

Umami Cloud

### Which browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

Umami Cloud

**Comment by mikecao** [comment]
How are you sending your request? The header is there.

![image](https://github.com/umami-software/umami/assets/477975/20125198-04aa-45f5-88e2-f55a8215245b)

**Comment by hisune** [comment]
I feel the same. It seems that it's not because of CORS; it’s due to the API data HTTP response error 500.

![image](https://github.com/umami-software/umami/assets/7941669/0715f04f-2222-4cde-aaa6-dd8d9f9d157b)

![image](https://github.com/umami-software/umami/assets/7941669/32e02cd4-1b2b-4c67-bf42-cd04d5d37c0b)

**Comment by notramo** [comment]
Turns out, it was incorrectly configured, and HTTP 400 was returned, but since it does not have CORS headers, Firefox devtools indicated the CORS errors in a way that it was grabbing attention more than the 400 error.

I would still recommend sending CORS headers with HTTP errors, to not confuse CORS error with the real error.

**Comment by notramo** [comment]
It's still relevant.
