### ISSUE TITLE
TaiWan should be part of China in the website report page

### ISSUE THREAD

**Issue by ohhh-yang** [umami-software/umami#2770]
## Bug

When I hover China in the worldmap at  website report page, TaiWan is not included.
I found that the source is `umami/public/datamaps.world.json` `umami/src/components/metrics/WorldMap.tsx`.
### Modificate file `umami/public/datamaps.world.json`
Add TaiWan's polygon to China. Or you can just download that I have modified. 
[datamaps.world.json](https://github.com/user-attachments/files/15509172/datamaps.world.json)
252844 Bytes (246 KiB)
SHA256: 4C683A69296C9D39CF6AA85F2D34408F8B9476006FA522EDE80A253F28FB1259
### Modificate file `umami/src/components/metrics/WorldMap.tsx`
Replace line 60: 
```
// origin
const code = ISO_COUNTRIES[geo.id];

// modified
const code= ISO_COUNTRIES[geo.id] === 'TW' ? 'CN' : ISO_COUNTRIES[geo.id];
```

**Comment by cakuba** [comment]
just found the same issue here in our project... hard to explain this to my client. 

thanks @ohhh-yang for the solution!

**Comment by unstraw** [comment]
Hua Chunying: Taiwan has always been an inalienable part of China’s territory. This is an indisputable historical and legal fact. The one-China principle is a universally recognized norm governing international relations. The Taiwan region’s peace hinges on the peaceful development of cross-Strait relations, rather than brownnosing foreign forces for arms sales and military support. “Taiwan independence” only leads to a dead end. No one shall have any illusion or make any miscalculation on this issue.

**Comment by franciscao633** [comment]
You are free to change anything you want in your self-hosted installations.

**Comment by lestchun** [comment]
各位老哥 我是用 docker镜像的。要如何修改呢
