### ISSUE TITLE
Data is not sorted correctly 

### ISSUE THREAD

**Issue by delemeator** [umami-software/umami#2897]
### Describe the Bug

It seems that there is some data sorting issue in 2.13.0 - I did not have this problem in 2.12.1

Compare page:
![image](https://github.com/user-attachments/assets/9fae5ceb-3ae6-4d3d-87db-331033a90303)

Sessions page:
![image](https://github.com/user-attachments/assets/6b464490-9b22-4cf7-98ed-d27e91810563)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.13.0

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Self hosted postgres + kubernetes

**Comment by eroc1990** [comment]
Seconding this with my own screenshots. The first is post v2.13.0 update:
![image](https://github.com/user-attachments/assets/d4e36e08-cc5d-43cb-82d5-ae242417afaa)

And the second is after rolling back to postgresql-v2.12.1
![image](https://github.com/user-attachments/assets/3a9f909e-0589-4951-9ad3-d07520b986be)

Something seems to not be parsing the data correctly and is causing output issues.

Setup is identical as above except running on Docker instead of Kubernetes, and testing within Firefox instead of Chrome.

**Comment by eroc1990** [comment]
#2898

**Comment by franciscao633** [comment]
We will get a fix patched asap. Thanks for reporting.

**Comment by mikecao** [comment]
What timezone are you using and what timezone is your database using?

**Comment by mikecao** [comment]
Fixed in v2.13.1
