### ISSUE TITLE
The data shown in the chart is incomplete

### ISSUE THREAD

**Issue by cottage** [umami-software/umami#2902]
### Describe the Bug

Data before 8am is not displayed (This is yesterday's data, and my timezone is Asia/Shanghai):
![1](https://github.com/user-attachments/assets/47633134-59bb-402a-8ac6-ba608914b6d8)

If I change the timezone such as America/New_York, nothing is displayed(This is today‘s data):
![2](https://github.com/user-attachments/assets/23f71bfa-2103-4bac-88bb-2d10476994a3)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.13.0

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Installing from source

**Comment by kyle1373** [comment]
Can confirm that this issue is also happening to me. Here is an instance of an umami instance using the old version:

![image](https://github.com/user-attachments/assets/17f9d5a8-2634-4cba-983f-495fdb8120e9)

And here is an instance with the same site but in the new version:

![image](https://github.com/user-attachments/assets/b88a7544-2148-4ba0-b97e-399cfab5153e)

**Comment by RoversX** [comment]
Same issue

**Comment by mikecao** [comment]
Fixed in v2.13.1
