### ISSUE TITLE
currentRef is always resolves to referrer

### ISSUE THREAD

**Issue by condemil** [umami-software/umami#3016]
### Describe the Bug

I was reviewing the tracker source code and found a suspicious check on the [following line](https://github.com/umami-software/umami/blob/v2.13.2/src/tracker/index.js#L262):

```js
let currentRef = referrer !== hostname ? referrer : '';
```

The hostname in here is `location.hostname`, which is just the host part of url (without port). And the referrer is `document.referrer` which is the full url. I see it as a potential bug as i always resolves to true.

### Database

Umami Cloud

**Comment by franciscao633** [comment]
Its just a condition to prevent the hostname of your website from being recorded as a referrer. Taking a quick look at the docs for [document.referrer](https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer), I'm guessing this note below can potentially be an issue? But I think your correct, since once your on the website, `handlePush` will determine the `currentRef`.

```
If the user navigated to the page via a link like <a href="https://www.w3.org/">W3</a>, then it will output the previous domain like developer.mozilla.org. If the user navigated to the page directly, it will output an empty string.
```

It is working since umami.is doesn't refer to itself, but it will probably work with the below?

`let currentRef = referrer`

**Comment by condemil** [comment]
Right, `let currentRef = referrer;` should be equal to the current behavior.

That means when the user browse through the website the previous url will be recorded as the referrer as there is no hostname check.

If you want to prevent sending referrer for the same hostname there should be some logic to extract hostname from the `document.referrer` and compare it with `location.hostname`.

**Comment by condemil** [comment]
Just to clarify, I'm talking about the case when the user navigates through full page refresh (like <a href=...> links), not SPA websites.
