### ISSUE TITLE
Documentation: Minimum Node.js Version Update

### ISSUE THREAD

**Issue by yibudak** [umami-software/umami#3070]
### Describe the Bug

Hello,

The documentation for Umami states that the minimum required Node.js version is “>=18.17.” However, the Umami 2.14.0 version does not complete the “yarn install” command because it requires “Node.js >= 18.18.0.”

### Database

MySQL

### Relevant log output

```shell
umami:/opt/umami# yarn install
yarn install v1.22.19
warning ../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning chart.js@4.4.6: The engine "pnpm" appears to be invalid.
error @typescript-eslint/eslint-plugin@8.15.0: The engine "node" is incompatible with this module. Expected version "^18.18.0 || ^20.9.0 || >=21.1.0". Got "18.17.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Which Umami version are you using? (if relevant)

2.14.0

### How are you deploying your application? (if relevant)

Self-deploy

**Comment by franciscao633** [comment]
Thanks for catching this. All docs in on the website have been updated to reflect this.

**Comment by eightysixed** [comment]
> Thanks for catching this. All docs in on the website have been updated to reflect this.

[This](https://umami.is/docs/v1/install)was the first result on Google when I searched for `what version of node umami`.

I was only even checking that because the website still says 18, when even v20 is EOL in just a few months. 

Is v22 (current LTS) supported? What's the recommendation? I can't Reopen this and it's a general enough question it might deserve it's own, new question :) I'll open that. Feel free to close either/both/neither :)
